### ISSUE TITLE
Google login error

### ISSUE THREAD

**Issue by AbdealiLoKo** [IAR-Webops/IITMConnect#15]
Keeps giving `The googleplus gender field is required.`

**Comment by yashmurty** [comment]
@AbdealiJK, you can get rid of this issue by setting your gender in Google account settings. Let me know if the issue persists.

**Comment by AbdealiLoKo** [comment]
Although this is a solution - it;s not a very nice one. It may be more user friendly to have it as an optional field ?

**Comment by yashmurty** [comment]
@AbdealiJK, I think in the future when this platform is big enough, various institute teams might need that info for targeted solutions, I think to avoid the hassle of getting this information at that time, it's better to have it mandatory now itself. 

Besides both Linkedin and Facebook have this mandatory and give this information by default whenever someone logs in via them. 
After considering all of it for a while, I took the call of keeping it mandatory. 

Perhaps I should display an additional message in the debug for this, asking people to try logging in via facebook as an alternative, instead of going to the google accounts setting and changing it there.
